default-lease-time 600;
max-lease-time 7200;
authoritative;

# Give clients a DNS they can actually use (since we are not running a local DNS here)
option domain-name-servers 1.1.1.1, 8.8.8.8;

subnet 10.6.0.0 netmask 255.255.255.0 {
  range 10.6.0.51 10.6.0.200;
  option routers 10.6.0.1;
  option broadcast-address 10.6.0.255;
}
